name: Security Pipeline

on:
    push:
        branches: ["main"]

jobs:
    scan:
        runs-on: ubuntu-latest

        steps:
            # ========================
            # CHECKOUT CODE
            # ========================
            - name: Checkout code
              uses: actions/checkout@v4

            # ========================
            # INSTALL TRIVY
            # ========================
            - name: Install Trivy
              run: |
                  sudo apt-get update
                  sudo apt-get install -y curl

                  curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

            # ========================
            # FILESYSTEM SCAN
            # ========================
            - name: Trivy filesystem scan (JSON)
              run: trivy fs . \
                  -f json \
                  -o trivy-report.json \
                  --exit-code 0 \
                  --severity HIGH,CRITICAL

            # ========================
            # PYTHON SCRIPT
            # ========================
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Run Python analyzer
              run: python3 scripts/analyze_trivy.py

            # ========================
            # BANDIT
            # ========================
            - name: Install Bandit
              run: pip install bandit

            - name: Run Bandit scan
              run: bandit -r scripts/

            # ========================
            # SARIF SCAN
            # ========================
            - name: Trivy SARIF scan
              run: trivy fs . \
                  -f sarif \
                  -o trivy.sarif \
                  --exit-code 0 \
                  --severity HIGH,CRITICAL

            - name: Upload SARIF to GitHub Security
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: trivy.sarif

            # ========================
            # UPLOAD ARTIFACTS
            # ========================
            - name: Upload reports
              uses: actions/upload-artifact@v4
              with:
                  name: security-reports
                  path: |
                      trivy-report.json
                      trivy.sarif
